# Copied from https://github.com/jonrohan/add-to-memex/blob/main/.github/workflows/add-to-inbox.yml
name: Move to Work Project

on:
  workflow_dispatch:
  push:
  schedule:
    # runs every 1 hour
    - cron:  '0 * * * *'

jobs:
  my-pull-requests:
    runs-on: ubuntu-latest

    steps:
      - name: Find my pull requests
        id: pull-requests
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const query = `{
              viewer {
                login
                pullRequests(first: 100, states: OPEN) {
                  edges {
                    node {
                      id
                      repository {
                        owner {
                          login
                        }
                      }
                    }
                  }
                }
              }
            }`
            const result = await github.graphql(query)
            return result.viewer.pullRequests.edges.filter(p => p.node.repository.owner.login == "github").map(p => p.node.id )
      - name: Add to project
        uses: actions/github-script@v6
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const prIds = ${{steps.pull-requests.outputs.result}};
            for (const id of prIds) {
              await github.graphql(`mutation($project:ID!,$issue:ID!) {
                  addProjectV2ItemById(input: {projectId: $project, contentId: $issue}) {
                    clientMutationId
                  }
                }`, { project: process.env.PROJECT_ID, issue: id })
            }
